search_space:
  umap_ncomp:
    tune_function: randint
    tune_parameters: [2, 360]
  umap_spread:
    tune_function: randint
    tune_parameters: [1, 30]
  umap_mdist:
    tune_function: uniform
    tune_parameters: [0.0, 0.99]
  umap_neigh:
    tune_function: randint
    tune_parameters: [2, 201]
initial_params:
  - umap_ncomp: 200
    umap_spread: 1
    umap_mdist: 0.1
    umap_neigh: 15