estimators:
- algorithm: RandomForest
  kwargs:
    n_estimators: 100
  name: randomforest-100
  num_runs: 10
- algorithm: KNN
  kwargs:
    n_neighbors: 5
  name: KNN-5
  num_runs: 1
- algorithm: SVM
  kwargs:
    C: 1.0
    kernel: rbf
  name: SVM-rbf-C1.0
  num_runs: 1
extra:
  in_use_features:
  - accel-x
  - accel-y
  - accel-z
  - gyro-x
  - gyro-y
  - gyro-z
  reduce_on: all
  report_reducer_weight: true
  save_reducer: false
  scale_on: train
reducer:
  algorithm: convtae1d
  kwargs:
    batch_size: 128
    cuda_device_name: cuda:0
    extra_properties:
      down_HL: 0
      kernel_size: 3
      num_CL: 4
      num_HL: 2
      optimizer_lr: 3.1603563154924165e-05
      optimizer_weight_decay: 2.787383576873575e-06
      size_CL: 17
      size_HL: 150
    latent_dim: 546
    model_lambda: 2.52859854058608
    model_name: ConvTAE_def
    num_epochs: 20000
    patience: 10
    save_frequency: 20001
    save_tag: 0
  name: AE
  use_y: true
reducer_dataset:
- kuhar.standartized_balanced[train]
- kuhar.standartized_balanced[validation]
test_dataset:
- kuhar.standartized_balanced[test]
train_dataset:
- kuhar.standartized_balanced[train]
- kuhar.standartized_balanced[validation]
transforms: []
version: '1.0'
