estimators:
- algorithm: RandomForest
  kwargs:
    n_estimators: 100
  name: randomforest-100
  num_runs: 10
- algorithm: KNN
  kwargs:
    n_neighbors: 5
  name: KNN-5
  num_runs: 1
- algorithm: SVM
  kwargs:
    C: 1.0
    kernel: rbf
  name: SVM-rbf-C1.0
  num_runs: 1
extra:
  in_use_features:
  - accel-x
  - accel-y
  - accel-z
  - gyro-x
  - gyro-y
  - gyro-z
  reduce_on: all
  report_pydrmetrics: true
  report_reducer_weight: true
  save_reducer: false
  scale_on: train
reducer:
  algorithm: convtae1d
  kwargs:
    batch_size: 64
    cuda_device_name: cuda:0
    extra_properties:
      down_HL: 0
      kernel_size: 4
      num_CL: 3
      num_HL: 3
      optimizer_lr: 0.0001244984912195
      optimizer_weight_decay: 9.729961705008592e-06
      size_CL: 10
      size_HL: 150
    latent_dim: 9
    model_lambda: 2.3761119596957947
    model_name: ConvTAE_def
    num_epochs: 20000
    patience: 10
  name: AE
  use_y: true
reducer_dataset:
- realworld_waist.standartized_balanced[train]
- realworld_waist.standartized_balanced[validation]
test_dataset:
- realworld_waist.standartized_balanced[test]
train_dataset:
- realworld_waist.standartized_balanced[train]
- realworld_waist.standartized_balanced[validation]
transforms: []
version: '1.0'
